config/routes.rb
Butcher::Application.routes.draw do
  resources :words

  root 'words#index'

end

app/models/attr.rb
class Attr
  include Mongoid::Document
  field :name
  field :meaning

  index :name => 1
  index :meaning => 1

  validates :name, :presence => true
  validates :meaning, :presence => true
end

app/models/chop.rb
#!/usr/bin/env ruby
require 'pp'

$min_word_len = 0  #minmal match length for a word, 0 = match anything.
$mongo ||= false
$debug ||= false
$db_file ||="config/mongoid.yml"

if $mongo
  require 'mongoid'
  Mongoid.load!($db_file, :development)
  require_relative "./word.rb"
end

class ChopResult
  attr_accessor :words, :line_after

  def initialize
    @words=[]
    @line_after=""
  end
end

#data structure used here is ruby hash
class Dict
  attr_accessor :dict, :dict_tree
  def initialize
    @dict={}
    @dict_tree={}
  end

  def flush_wt
    @dict={}
    @dict_tree={}
  end

  def get_dict_word word
    @dict[word]
  end

  def save_word_to_db word, freq, attr
    w=Word.new
    w.name = word
    w.freq = freq
    w.attr = attr
    w.save
    puts word if $debug
  end

  def load_from_mongo
    Word.each do |w|
      build_tree w.name, w.freq, w.attr
    end
  end
  
  def build_tree word, freq, attr
    @dict[word]=[freq, attr]
    #make the dict tree, by walking down the branch
    wordlen =  word.length
    wordindex = 0
    dc = @dict_tree
     
    while wordlen > wordindex
      char = word[wordindex]
      if dc[char].nil?
        dc[char] = {} #new branch
        dc[char]["_"]=[freq, attr]
      else
        dc = dc[char] #walk the old branch
      end
      wordindex += 1
    end
  end
  
  def load_from_file fn, do_build_tree=true
    file = File.new(fn, "r")
    while (line = file.gets)
      elems = line.split(" ")
      word = elems[0] #first is word itself
      freq = elems[1] #2nd is freq of appearnce.
      attr = elems[2] #3rd is word attribute.
      next if word.nil?
      save_word_to_db(word, freq, attr) if $mongo
      build_tree(word, freq, attr) if do_build_tree
    end
  end

  def mw? word #complete match a word
    ! @dict[word].nil?
  end

  def mt? word #match a tree, a part of a word
    wl = word.length
    dt = @dict_tree
    
    #walk down the tree branch
    for i in 0..(wl-1)
      dt=dt[word[i]]
      return false if dt.nil?
    end
    return dt.size > 1
  end

end


#there are some different cutting rules exisit:
# http://baike.baidu.com/view/19109.htm

class Chopper

  def initialize dict
    @dict = dict
  end

  def chop line
    chop_basic line
  end

  #find all matches and record there indexes and length.
  def chop_basic line
    i= 0
    wordlen = 1
    words_index=[]
    words_length=[]
    found_words=[]
    temp_word=nil
    temp_length=0

    cr = ChopResult.new

    while i < line.length
      while i + wordlen <= line.length  #break if try_word over the boundry of a line
        try_word=line[i, wordlen]
        mt=@dict.mt? try_word
        mw=@dict.mw? try_word

        if mw #if we match a word, yes-> match tree?{yes-> wordlen++ , no -> found word}, 
          temp_word = try_word; temp_length = wordlen; temp_index=i
          if mt
          else
            #found a word, and save output
            if !temp_word.nil?
              found_words << temp_word; words_index << temp_index; words_length << temp_length
              cr.words << temp_word; cr.line_after = cr.line_after + "|" + line[temp_index, temp_length]
              i = i + wordlen - 1 ; temp_word = nil
              break
            else
              #bad luck nothing found
            end
          end
        else  # not match a word, if match a tree, yes -> 
          if mt
            #not match a word, but match a tree, we inc the word length
          else
            #not a tree, not a word
            if !temp_word.nil?
              found_words << temp_word; words_index << temp_index; words_length << temp_length
              cr.words << temp_word; cr.line_after = cr.line_after + "|" + line[temp_index, temp_length]
              i = i + temp_length - 1 ; temp_word = nil
              break
            else
              #bad luck nothing found
              cr.line_after = cr.line_after + line[i]
              break #no word, no tree #orpahn char. #TODO take care orphan
            end
          end
        end #end of big if
        wordlen += 1
      end
      # if so we reset wordlen and increment i. and go to next loop
      i+=1; wordlen=1
    
      #end of a line, take care of last word if have
      if !temp_word.nil?
        found_words << temp_word; words_index << temp_index; words_length << temp_length
        cr.words << temp_word; cr.line_after = cr.line_after + "|" + line[temp_index, temp_length]
        temp_word = nil
        break
      end
      ##
    end 

    @words_array = []
    for i in 0..(words_index.length-1)
      if @words_array[words_index[i]].nil?
        @words_array[words_index[i]]=[]
      end
      @words_array[words_index[i]] << words_length[i]
    end
    @words_array

    cr
  end

  def reassemble_left
     
  end

  def reassemble_right

  end
  
  def reassemble_freq

  end

  def reassemble_center #via both direction

  end

end

app/models/word.rb
class Word
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name
  field :freq, type: Integer
  field :attr
  field :is_custom, type: Boolean, default: false
  field :attr2, type: String, default: ""

  index :freq => 1
  index :name => 1

  validates :name, :presence => true
  validates :freq, :presence => true
  validates :attr, :presence => true
  
  def get_attr
    attr=Attr.where(:name => self.attr).first
    return '' if attr.nil?
    return attr.meaning
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @page_size = 200

    @range_start = params[:page].nil? ? 0 : params[:page].to_i * @page_size
    @range_end = @range_start + @page_size
  
    words = Word.all

    if !params[:attr].nil?
      words = words.where(:attr => params[:attr])
    end

    if params[:sort] == "freq_asc"
      @words = words.asc("freq").page(params[:page]).per(@page_size)
    elsif params[:sort] == "freq_dsc"
      @words = words.desc("freq").page(params[:page]).per(@page_size)
    elsif params[:sort] == "attr_asc"
      @words = words.asc("attr").page(params[:page]).per(@page_size)
    elsif params[:sort] == "attr_dsc"
      @words = words.desc("attr").page(params[:page]).per(@page_size)
    else
      @words = words.desc("freq").page(params[:page]).per(@page_size)
    end
    
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render action: 'show', status: :created, location: @word }
      else
        format.html { render action: 'new' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name, :freq, :attr)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Butcher</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <style>
      body {
          padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
  </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">Butcher</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<div class="container">
  <%= yield %>
</div> <!-- /container -->


</body>
</html>

app/views/words/_form.html.erb
<%= simple_form_for(@word) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :freq %>
    <%= f.input :attr %>
    <%= f.input :is_custom %>
    <%= f.input :attr2 %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h3>Word count: <%= @words.count %></h2>
<p> Listing Word from <%=@range_start%> to <%=@range_end%> </p>

<%= link_to 'New Word', new_word_path, :class => "btn btn-primary" %>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>
        <% if params[:sort]=="name_asc" %>
          <%= link_to "Name", "?sort=name_dsc" %>
        <% else %>
          <%= link_to "Name", "?sort=name_asc" %>
        <% end %>
      </th>
      <th>
        <% if params[:sort]=="freq_asc" %>
          <%= link_to "Frequency", "?sort=freq_dsc" %>
        <% else %>
          <%= link_to "Frequency", "?sort=freq_asc" %>
        <% end %>
      </th>
      <th>
        <% if params[:sort]=="attr_asc" %>
          <%= link_to "Attr", "?sort=attr_dsc" %>
        <% else %>
          <%= link_to "Attr", "?sort=attr_asc" %>
        <% end %>
      </th>
      <th>custom?</th>
      <th>Attr2</th>
      <th>Controls</th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.name %></td>
        <td><%= word.freq %></td>
        <td><%= word.attr+", "%><%= link_to word.get_attr, "?attr=#{word.attr}" %></td>
        <td><%= word.is_custom %></td>
        <td><%= word.attr2 %></td>
        <td><%= link_to 'Show', word %> <%= link_to 'Edit', edit_word_path(word) %> <%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @words%>

<br>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @word.name %>
</p>

<p>
  <strong>Freq:</strong>
  <%= @word.freq %>
</p>

<p>
  <strong>Attr:</strong>
  <%= @word.attr %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>